language: C

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - INTERVAL_LIB=gaol
        - LP_LIB=soplex
        - STATIC_OR_SHARED=
        - STATIC_OR_SHARED_CMAKE=
    - os: linux
      compiler: gcc
      env:
        - INTERVAL_LIB=gaol
        - LP_LIB=none
        - STATIC_OR_SHARED=--enable-shared
        - STATIC_OR_SHARED_CMAKE=-DBUILD_SHARED_LIBS=ON
    - os: linux
      compiler: gcc
      env:
        - INTERVAL_LIB=filib
        - LP_LIB=soplex
        - STATIC_OR_SHARED=
        - STATIC_OR_SHARED_CMAKE=
    - os: linux
      compiler: gcc
      env:
        - INTERVAL_LIB=direct
        - LP_LIB=soplex
        - STATIC_OR_SHARED=
        - STATIC_OR_SHARED_CMAKE=
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - INTERVAL_LIB=gaol
        - LP_LIB=soplex
        - STATIC_OR_SHARED=
        - STATIC_OR_SHARED_CMAKE=
        - CXXFLAGS=-std=c++11
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - INTERVAL_LIB=gaol
        - LP_LIB=none
        - STATIC_OR_SHARED=--enable-shared
        - STATIC_OR_SHARED_CMAKE=-DBUILD_SHARED_LIBS=ON
        - CXXFLAGS=-std=c++11

jobs:
  allow_failures:
    - os: linux
      compiler: gcc
      env:
        - INTERVAL_LIB=direct
        - LP_LIB=soplex
        - STATIC_OR_SHARED=
        - STATIC_OR_SHARED_CMAKE=

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev

# need this to install dependencies on osx
before_install:
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install flex bison cppunit; fi

install:
  - ./waf configure --prefix=$HOME ${STATIC_OR_SHARED} --interval-lib=${INTERVAL_LIB} --lp-lib=${LP_LIB} || cat __build__/*.log
  - ./waf build install clean

# command to run tests
# TODO: add nonreg tests
script:
  - ./waf utest
  - mkdir build
  - cd build
  - cmake ${STATIC_OR_SHARED_CMAKE} -DINTERVAL_LIB=${INTERVAL_LIB} -DLP_LIB=${LP_LIB} ..
  - make
  - make check
#  - __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex8_5_2.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 100 1

after_failure:
  - cat __build__/*.log
