language: C

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
      osx_image: xcode7.3
  allow_failures: # temporary
    - os: osx

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install python flex bison cppunit; fi

install: 
  - cd plugins/optim/; tar xvf soplex-1.7.1.tar && cd soplex-1.7.1 && make install && cd ../../..
  - ./waf configure --with-optim --with-soplex=$PWD/plugins/optim/soplex-1.7.1 --with-affine --with-optim
  - sudo ./waf install
  - export PKG_CONFIG_PATH=/usr/local/share/pkgconfig/
  - cd tests/ && make utest && cd ..
  - cd plugins/optim/tests/ && make nonreg && cd ../../..

# command to run tests
script:  
#  - __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex8_5_2.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 100 1
  - cd tests/ && ./utest && cd ..
#  - cd plugins/optim/tests/ && ./nonreg nonreg-travis-soplex-filib.res && cd ../../..

