language: C

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - TEST_INTERVAL_LIB=gaol
        - STATIC_OR_SHARED=
        - PLUGINS=--with-optim --optim-lib=soplex
    - os: linux
      compiler: gcc
      env:
        - TEST_INTERVAL_LIB=gaol
        - STATIC_OR_SHARED=--enable-shared
        - PLUGINS=
    - os: linux
      compiler: gcc
      env:
        - TEST_INTERVAL_LIB=filib
        - STATIC_OR_SHARED=
        - PLUGINS=--with-optim --optim-lib=soplex
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env:
        - TEST_INTERVAL_LIB=gaol
        - STATIC_OR_SHARED=
        - PLUGINS=--with-optim --optim-lib=soplex

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install python flex bison cppunit; fi

# TODO add --affine when tests are fixed
install: 
  - ./waf configure --prefix=$HOME ${STATIC_OR_SHARED} --interval-lib=${TEST_INTERVAL_LIB} ${PLUGINS} || cat __build__/*.log
  - ./waf build install clean

# command to run tests
# TODO: add nonreg tests
script:  
  - ./waf utest
#  - __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex8_5_2.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 100 1

after_failure:
  - cat __build__/*.log
